sudo: required
services:
  - docker

before_install:
  - docker build -t akshay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akshay/react-test npm run test -- --coverage

after_success:
  - docker build -t akshaybabar/client ./client
  - docker build -t akshaybabar/nginx ./nginx
  - docker build -t akshaybabar/server ./server
  - docker build -t akshaybabar/worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akshaybabar/client
  - docker push akshaybabar/nginx
  - docker push akshaybabar/server
  - docker push akshaybabar/worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-us-east-2-358819384619"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"